using System;
using System.Drawing;
using System.Windows.Forms;
using System.Diagnostics;



namespace DIePlommm
{
    public partial class MainForm : Form
    {
        /**
         * Переменные
         */
        TrafficIntensityEstimate tie; //отвечает за информацию которая будет появляться на экране
        Timer timer; //таймер который отвечает за обновление информации
        bool networkConnection; //позволит определять есть ли соеденение                
        
        /**<summary>
         * начало программы
         * </summary>
         */
        public static void Main()
        { 
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Form f = new MainForm();
            Application.Run(f);
        }


       
        /**
         * <summary>
         * Конструктор класса форм. 
         * Заготавливает основу формы
         * </summary>
         */
        public MainForm()
        {
            //---------------------------------AutoGenerated---------------------------------------------
            InitializeComponent();

            //-------------------------------Экземпляр нашего класса-------------------------------------
            tie = new TrafficIntensityEstimate();

            //-----------------------------Выводим интерфейсы в ListBox----------------------------------
            listBox1.DataSource = tie.GetNetworkInterfaces();

            //-------------------------------------------------------------------------------------------
            listBox1.SelectedIndexChanged += ChangeNetworkInterface;
            networkConnection = IsNetworkConnection();
            TurnOnZoom();

            //-------------------------------Определяем работу таймера-----------------------------------
            timer = new Timer();
            timer.Tick += OutputData;
            ChangeInterval();
            timer.Start();
        }


        /**
         * <summary>
         * Метод для постоянного обновления значения интенсивности трафика
         * Метод для Timer.Tick
         * Рисуется график и выводится текущее значение интенсивности трафика
         * </summary>
         */
        private void OutputData(object sender, EventArgs e)
        {
            if (networkConnection)
            {
                //------------------------ИНИЦИАЛИЩАЦИЯ ПЕРЕМЕННЫХ--------------------
                double bytes = tie.GetInputTraffic();
                double kBit = Math.Round((bytes / 125), 3);
                double mBit = Math.Round((bytes / 125000), 3);


                //---------------------ВЫВОД ИНФОРМАЦИИ-------------------------------
                string outputTextBoxMbits = mBit.ToString() + "Mbit/sec";
                string outputTextBoxKbits = kBit.ToString() + "Kbit/sec";


                if (mBit <= 0.5)                {
                    textBox1.Text = outputTextBoxKbits;
                }
                else{
                    textBox1.Text = outputTextBoxMbits;
                }
                chartMbits.Series[0].Points.AddXY(DateTime.Now.ToShortTimeString(), mBit);
            }
            else
            {
                textBox1.Text = "NotConnection";
                networkConnection = IsNetworkConnection();
            }
        }



        /**
         * <summary>
         * Реагирует на изменения выбраного сетевого интерфейса в listBox1
         * </summary>
         */
        private void ChangeNetworkInterface(object sender, EventArgs e)
        {
            tie.SetNetworkInterface(listBox1.SelectedItem as String);
            chartMbits.Series[0].Points.Clear();

            networkConnection = IsNetworkConnection();
        }



        /**
         * <summary>
         * Метод проверяет есть ли подключение по данному сетевому интерфейсу.
         * Если нагрузка нулевая, то подключение отсутсвует
         * </summary>
         */
        private bool IsNetworkConnection()
        {
           if (tie.IsNetworkConnection())
            {
                labelStatus.ForeColor = Color.Green;
                labelStatus.Text = "Connection";
                return true;

            }
            labelStatus.ForeColor = Color.Red;
            labelStatus.Text = "Not Connection";
            return false;
        }


        /**
         * <summary>
         * Метод реагирует на нажатие кнопки buttonResetZoom
         * Убирает последний зум по X и Y
         * </summary>
         */
        private void ButtonResetZoom_Click(object sender, EventArgs e)
        {
            chartMbits.ChartAreas[0].AxisY.ScaleView.ZoomReset();
            chartMbits.ChartAreas[0].AxisX.ScaleView.ZoomReset();
        }


        /**
         * <summary>
         * Метод реагирует на нажатие клавиши buttonClearGraph
         * Очищает график
         * </summary>
         */
        private void ButtonClearGraph_Click(object sender, EventArgs e)
        {
            chartMbits.Series[0].Points.Clear();
        }


        /**
         * <summary>
         * Метод реагирует на изменение значения в numericUpDown1
         * </summary>
         */
        private void NumericUpDown1_ValueChanged(object sender, EventArgs e)
        {
            ChangeInterval();
        }


        /**
         * <summary>
         * Метод для изменения интервала таймера в зависимости от значения в numericUpDown1
         * Так же выводит в labelIntervalError текст о том большой ли интервал был выбран. 
         * В моем понимании интервал больше 5 может стать большой проблемой в качестве полученных данных.
         * Неизвестно что произошло за эти 4 секунды. 3 это край край
         * </summary>
         */
        private void ChangeInterval()
        {
            timer.Interval = (int)numericUpDown1.Value * 1000;

            if ((int)numericUpDown1.Value >= 4)
            {
                labelIntervalError.ForeColor = Color.Red;
                labelIntervalError.Text = "Данные могут быть некоректны";
            }
            else
            {
                labelIntervalError.ForeColor = Color.Green;
                labelIntervalError.Text = "Интервал в пределах разумного";
            }
        }

        /**
         * <summary>
         * Метод который включает возможность масштабирования графика
         * </summary>
         */
        private void TurnOnZoom()
        {
            //включаем зум по Х
            chartMbits.ChartAreas[0].CursorX.IsUserEnabled = true;
            chartMbits.ChartAreas[0].CursorX.IsUserSelectionEnabled = true;
            chartMbits.ChartAreas[0].AxisX.ScaleView.Zoomable = true;
            chartMbits.ChartAreas[0].AxisX.ScrollBar.IsPositionedInside = true;

            //включаем зум по Y
            chartMbits.ChartAreas[0].CursorY.IsUserEnabled = true;
            chartMbits.ChartAreas[0].CursorY.IsUserSelectionEnabled = true;
            chartMbits.ChartAreas[0].AxisY.ScaleView.Zoomable = true;
            chartMbits.ChartAreas[0].AxisY.ScrollBar.IsPositionedInside = true;
        }
    }
}
